### ISSUE TITLE
Unexpected token ' error on windows 

### ISSUE THREAD

**Issue by haseeb2k9** [chimame/search_ranking_checker_on_aws_lambda#2]
I'm getting this error on windows 

```
docker run --rm -v %cd%:/var/task lambci/lambda:nodejs8.10  index.handler '{"searchWord": "car", "siteDomain": "xyz.com"} | jq '.searchResults'
jq: error: syntax error, unexpected INVALID_CHARACTER, expecting $end (Windows cmd shell quoting issues?) at <top-level>, line 1:
'.searchResults'
jq: 1 compile error
START RequestId: xxxxxx-xxxxxx-xxxx-xxxx-xxxxxxxxxx Version: $LATEST
Unable to parse input as json: Unexpected token ' in JSON at position 0: SyntaxError
    at JSON.parse (<anonymous>)
END RequestId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
REPORT RequestId: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx Duration: 4.75 ms       Billed Duration: 100 ms Memory Size: 1536 MB    Max Memory Used: 31 MB
write /dev/stdout: The pipe is being closed.
```

here is the script.

```

'use strict'
const launchChrome = require('@serverless-chrome/lambda')
const CDP = require('chrome-remote-interface')
const puppeteer = require('puppeteer')
exports.handler = async (event, context, callback) => {
  let slsChrome = null
  let browser = null
  let page = null
  try {
    slsChrome = await launchChrome()
    browser = await puppeteer.connect({
      browserWSEndpoint: (await CDP.Version()).webSocketDebuggerUrl
    })
    const context = browser.defaultBrowserContext()
    const page = await context.newPage()
    await page.setExtraHTTPHeaders({ 'Accept-Language': 'en-GB' })
    await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36')
    await page.goto('https://www.google.com/', { waitUntil: 'networkidle0' })
    const searchWord = encodeURIComponent(event.searchWord)
    await page.goto('https://www.google.com/search?q=${searchWord}', { waitUntil: 'domcontentloaded' })
    await page.waitFor(1000)
    const screenShot = await page.screenshot({fullPage: true})
    const searchResults = await page.evaluate(() => {
      const ret = []
      const nodeList = document.querySelectorAll("div#search h3")
      nodeList.forEach(node => {
        ret.push(node.innerText)
      })
      return ret
    })
    await page.waitFor(1000)
    return callback(null, {result: 'OK', searchResults: searchResults, screenShot: screenShot.toString('hex')})
  } catch (err) {
    // console.error(err)
    return callback(null, JSON.stringify({ result: 'NG' }))
  } finally {
    if (page) {
      await page.close()
    }
    if (browser) {
      await browser.disconnect()
    }
    if (slsChrome) {
      await slsChrome.kill()
    }
  }
}

```

**Comment by chimame** [comment]
hi @haseeb2k9 

It's your simple command mistake.
I forgot to close the single quote before the jq command.

**Comment by haseeb2k9** [comment]
Hi @chimame  

I run the above code on lambda it gives Success and Null in **Node.js 8.10**

here is Log Output 

`START RequestId:  Version: $LATEST
2019-03-13T09:37:16.443Z		(node:1) UnhandledPromiseRejectionWarning: Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:199:40
    at Generator.next (<anonymous>)
    at step (/var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:69:193)
    at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:69:439
    at new Promise (<anonymous>)
    at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:69:101
    at Promise (/var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:220:23)
2019-03-13T09:37:16.461Z		(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2019-03-13T09:37:16.461Z	(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
END RequestId: 
REPORT RequestId: 	Duration: 509.77 ms	Billed Duration: 600 ms 	Memory Size: 128 MB	Max Memory Used: 85 MB	
`

but when it runs on Node .js 6.10 it giv error 
`{
  "errorMessage": "Unexpected token (",
  "errorType": "SyntaxError",
  "stackTrace": [
    "                        ^",
    "SyntaxError: Unexpected token (",
    "createScript (vm.js:56:10)",
    "Object.runInThisContext (vm.js:97:10)",
    "Module._compile (module.js:542:28)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]
}`

here is Log Output

`START RequestId:  Version: $LATEST
Syntax error in module 'index': SyntaxError
exports.handler = async (event, context, callback) => {
                        ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: 
REPORT RequestId: 	Duration: 103.47 ms	Billed Duration: 200 ms 	Memory Size: 128 MB	Max Memory Used: 64 MB	`
